# Generated by Django 3.0.7 on 2020-06-18 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produc_type', models.CharField(choices=[('Whisky', (('BLENDED SCOTCH', 'BLENDED SCOTCH'), ('BOURBON WHISKIES', 'BOURBON WHISKIES'), ('IRISH WHISKIES', 'IRISH WHISKIES'), ('SINGLE MALT', 'SINGLE MALT'), ('TENESEE WHISKIES', 'TENESEE WHISKIES'))), ('vodka', 'vodka'), ('Wine', (('RED WINE', 'RED WINE'), ('WHITE WINE', 'WHITE WINE'), ('ROSE WINE', 'ROSE WINE'))), ('Champagne', 'Champagne'), ('Brandy', 'Brandy'), ('Cognac', 'Cognac'), ('Beer', (('CIDER', 'CIDER'), ('LAGER', 'LAGER'), ('MALT', 'MALT'), ('DRAUGHT', 'DRAUGHT'))), ('Tequila', 'Tequila'), ('Rum', 'Rum'), ('Gin', 'Gin'), ('Liquer', 'Liquer'), ('Extras', 'Extras')], default=None, max_length=255)),
                ('picture', models.ImageField(default=None, upload_to='Uploads')),
                ('name', models.CharField(default=None, max_length=200)),
                ('capacity', models.CharField(max_length=200)),
                ('cash', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
