# Generated by Django 3.0.7 on 2020-06-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='product',
        ),
    ]
